### ISSUE TITLE
Linking Errors due to not Compiling include/internal/*.cpp Files

### ISSUE THREAD

**Issue by hstalker** [mesonbuild/catch#2]
When attempting to use this meson patch for Catch you will encounter link errors as a result of the implementation code contained in `include/internal/*.cpp` files not being compiled or baked into the `catch_dep` dependency in any way. I was able to reproduce this problem under a very simple test project under both windows-msys2/g++ and debian/g++.

A few Catch issues that discuss this problem:
 * https://github.com/catchorg/Catch2/issues/1097
 * https://github.com/catchorg/Catch2/issues/1085
 * https://github.com/catchorg/Catch2/issues/1142

It appears there are two recommended solutions by the developers. The first is to use the `single_include` directory instead of `include` that bundles *all* of the catch code into a single monolithic file; this is a one line fix. This unfortunately increases build times due to having to compile all of catch every time the monolithic `catch.hpp` is included. 
The second would be to compile the .cpp files present in `include/internal` in our `build.meson`, with the obvious downside being that it would increase maintenance effort due to making the meson build process more complex (e.g. having to support multiple OSs and compilers etc.) as well as making the build.meson reliant on the internal file structure of Catch. The upside being that it would reduce repeated compilation and therefore build times.

Do the maintainers/other contributors have any thoughts as to what direction to take?

**Comment by sarum9in** [comment]
@jeandet was the original author of this wrap and might have something to say.

**Comment by jeandet** [comment]
@hstalker @sarum9in, that's an error from my side I didn't have time to check it since it is on Wrapdb, I'll fix that ASAP. Sorry for the mistake.
